### PR TITLE
Product & Product type

### PR DESCRIPTION
**Pull request by agourlay**
I will ```try``` to do another check to ensure correctness before declaring this mergeable from my side.
Nevertheless you can still have a look at it and help me hunt problems.

Disclaimer: I turned into a typing robot at some point :)

### CODE REVIEW

**Comment by mmoelli** [comment]
But you did great... ;)

**Comment by emmenko** [comment]
Small PR next time!

**Comment by hajoeichler** [comment]
@agourlay Do we apply some JSLint or alike on it?

**Comment by agourlay** [comment]
@hajoeichler so far no.

**Comment by hajoeichler** [comment]
Call me "picky" :smiling_imp: 
```
schemas/localized-enum-value.schema.json
 #1 Unexpected ','.
    "description": "The key of the value used as a programmatic identifier, e.g. in facets & filters.", // Line 10, Pos 105

schemas/plain-enum-value.schema.json
 #1 Unexpected ','.
    "description": "The key of the value used as a programmatic identifier, e.g. in facets & filters.", // Line 10, Pos 105

schemas/product-create.schema.json
 #1 Unexpected character '(space)'.
    } // Line 49, Pos 7

schemas/product-projection.schema.json
 #1 Unexpected character '(space)'.
    }, // Line 32, Pos 10

schemas/product-type-update.schema.json
 #1 Unexpected character '(space)'.
     // Line 138, Pos 9
 #2 Unexpected character '(space)'.
    "description":"It can update a LocalizableEnum attribute definition or a Set of LocalizableEnumType attribute definition.", // Line 180, Pos 134

schemas/product-update-error.schema.json
 #1 Unexpected character '(space)'.
    } // Line 113, Pos 15

schemas/product-update.schema.json
 #1 Unexpected character '(space)'.
    "description":"It can update a LocalizableEnum attribute definition or a Set of LocalizableEnumType attribute definition.", // Line 179, Pos 134
```

**Comment by agourlay** [comment]
@OlegIlyenko & @cneijenhuis 
could you have a quick look at this please :)

**Comment by cneijenhuis** [comment]
LRTM (Looks RAML to me).
I'll merge it :)

**Comment by agourlay** [comment]
:see_no_evil:

**Pull request merged**
