### PR TITLE
TravisCI; RAML, schema and example validation

### PR DESCRIPTION
**Pull request by nkuehn**
Hi everybody, as the TravisCI integration is working now and the first validation results showed that they are actual bugs let's merge this so the Travis builds have a meaning (currently it assumes ruby ;-)

### CODE REVIEW

**Comment by cneijenhuis** [comment]
There are my commits on the customer-files... I'd remove them from this PR :wink: 

Otherwise great! LGTM :+1:

**Comment by nkuehn** [comment]
sure. I had made them parallel to yours.

**Comment by cneijenhuis** [comment]
I don't have a strong opinion on whether a markdown validator is useful, but I'm leaning towards a no.
But I definitely hate having a line-length restriction. :wink: This is not code, it's free-form text. My editor can break lines perfectly fine, and nobody wants to re-set multiple linebreaks if they have to insert a word at the beginning of a paragraph...

**Comment by cneijenhuis** [comment]
Pls merge master. Except for markdown, everything should work now!

Would be great to merge this asap so it stays this way :wink:

**Comment by nkuehn** [comment]
hmm, not yet OK if the validator is to be believed.  

As halo's branch is not in master anyways (so the master travis is pointless anyways) I'll merge this now and to the improvements to the validation (generating the inlined schemata files, committing etc) in a new branch. 

Will check what the conflicts are, first.

**Comment by nkuehn** [comment]
TADA.  do we delete old branches? 

P.S. on the markdown validation: 
I think it makes sense (especially because most of the markdown is currently written directly in the YAML and not in an MD editor with syntax highlighting etc.), we just have to agree on how sharp or not to set the rules.  I'll create an issue to track the discussion.

**Comment by cneijenhuis** [comment]
Yes, we delete branches. But you could also keep working on it and open another PR from it, I guess?

Anyway, it passes now, right? :)

**Pull request merged**
